### ISSUE TITLE
The template loader cache problem

### ISSUE THREAD

**Issue by ali-khalili** [titpetric/minitpl#3]
Hi,

If you include a sub-view in your template and the main template doesn't change and only the sub-view which is included changes, the template loader compiler doesn't consider the change because it only consider time stamp of the main view not the sub-views included in the template.

**Comment by titpetric** [comment]
Hi, this is documented behaviour. In order to disable caching you should add `{*nocache*}` to the root template, or use the `load` directive instead of `include`.

1. [nocache documentation](https://github.com/titpetric/minitpl/blob/master/documentation/documentation_en.markdown#34-nocache),
2. [includes documentation](https://github.com/titpetric/minitpl/blob/master/documentation/documentation_en.markdown#16-includes)

let me know if you have some more questions :)

**Comment by ali-khalili** [comment]
Thanks :+1:
